---
# yamllint disable rule:line-length
###############################################################################
# Github Download
###############################################################################
# Download and validate archive release package from github, using specified
# version.
#
# Args:
#   _github_target: str - Full version (vx.x.x) to install.
#   _github_target_url: str - Download url for target release.
#   _github_archive: str - Local versioned archive location.
#   _github_staging_stat: stat - For existing staging location.
#   _github_cache_test_index: int - Current injected test archive item.

- name: 'Download | create staging directory'
  when: not _github_staging_stat.stat.exists
  ansible.builtin.file:
    path: '{{ github_staging_dir }}'
    owner: '{{ github_file_owner }}'
    group: '{{ github_file_group }}'
    mode: '0755'
    state: 'directory'

- name: 'Download | {{ github_repo_repo }} {{ _github_target }}'  # noqa name[template] show full repo version
  when: >
    not _github_archive_stat.stat.exists and
    not (github_testing_enable | default(false))
  ansible.builtin.get_url:
    url: '{{ _github_target_url }}'
    dest: '{{ _github_archive }}'
    owner: '{{ github_file_owner }}'
    group: '{{ github_file_group }}'
    mode: '{{ github_extract_mode }}'
    headers:
      Authorization: '{{ github_personal_access_token | default(omit) }}'
  register: _github_download
  until: _github_download is succeeded
  retries: '{{ github_download_retries }}'
  delay: 2

- name: 'Download'
  when: (github_testing_enable | default(false))
  block:
    - name: 'Download | inject downloaded archive'
      when: github_testing_archives | length > 0
      ansible.posix.synchronize:
        src: '{{ github_testing_archives[_github_cache_test_index | int] }}'
        dest: '{{ _github_archive }}'
        archive: false
        checksum: true

    - name: 'Download | inject archive permissions'
      ansible.builtin.file:
        path: '{{ _github_archive }}'
        owner: '{{ github_file_owner }}'
        group: '{{ github_file_group }}'
        mode: '{{ github_extract_mode }}'
        state: 'file'
