---
# yamllint disable rule:line-length
###############################################################################
# Unpack Github Archive
###############################################################################
# Create versioned directory and unpack 'complete' archive.
#
# Args:
#   _github_archive: str - local versioned archive location.
#   _github_dir: str - local versioned extract location.
#   _github_extract_stat: stat - for existing extract location.

- name: 'Extract | create extract directory'
  when: not _github_extract_stat.stat.exists
  ansible.builtin.file:
    path: '{{ _github_dir }}'
    owner: '{{ github_file_owner }}'
    group: '{{ github_file_group }}'
    mode: '{{ github_extract_mode }}'
    state: 'directory'

- name: 'Extract | unpack archive'
  when: not _github_extract_stat.stat.exists
  ansible.builtin.unarchive:
    src: '{{ _github_archive }}'
    remote_src: true
    dest: '{{ _github_dir }}'
    owner: '{{ github_file_owner | default("root", true) }}'
    group: '{{ github_file_group | default("root", true) }}'
    mode: '{{ github_extract_mode | default("0644", true) }}'
    extra_opts: '{{ github_extract_extra_opts | default(omit, true) }}'

- name: 'Extract | cleanup non-required archive source files'
  when: >
    not _github_extract_stat.stat.exists and
    github_extract_remove_files | length > 0
  ansible.builtin.file:
    path: '{{ _github_dir }}/{{ item }}'
    state: 'absent'
  loop: '{{ github_extract_remove_files }}'

- name: 'Extract | check for existing symlink'
  ansible.builtin.stat:
    path: '{{ github_extract_symlink_target }}'
  check_mode: true
  register: _github_symlink_stat

# Migrate files before removing symlink to old version.
- name: 'Extract | migrate'
  when: >
    _github_symlink_stat.stat.exists and
    github_extract_migrate_files | length > 0
  ansible.builtin.include_tasks: 'migrate.yml'
  loop: '{{ github_extract_migrate_files }}'

- name: 'Extract | symlink {{ _github_dir }} to {{ github_extract_symlink_target }}'  # noqa name[template] provide full symlink info
  when: github_extract_symlink_target
  ansible.builtin.file:
    src: '{{ _github_dir }}'
    dest: '{{ github_extract_symlink_target }}'
    owner: '{{ github_file_owner }}'
    group: '{{ github_file_group }}'
    force: true
    state: 'link'

- name: 'Extract | remove old versions'
  when: github_extract_delete_old_versions
  block:
    - name: 'Extract | find existing extracted archives'
      ansible.builtin.find:
        paths: '{{ github_extract_dest }}'
        file_type: 'directory'
        use_regex: true
        patterns:
          - '.*{{ github_repo_repo }}-.*'
        recurse: false
      register: _github_install_stat

    # Reverse index '-' as some repositories use - in names (paperless-ngx).
    - name: 'Extract | delete old versions'
      when: _github_target != item.path.split("-", -1)[-1]
      ansible.builtin.file:
        path: '{{ item.path }}'
        state: 'absent'
      loop: '{{ _github_install_stat.files }}'
      loop_control:
        label: '{{ item.path }}'

- name: 'Extract | cleanup staging archive'
  when: github_staging_clean
  ansible.builtin.file:
    path: '{{ _github_archive }}'
    state: 'absent'
