---
- name: 'Prep'
  ansible.builtin.include_tasks: 'prep.yml'
- name: 'Packages'
  ansible.builtin.include_tasks: 'packages.yml'
- name: 'Download'
  ansible.builtin.include_tasks: 'download.yml'
- name: 'Extract'
  ansible.builtin.include_tasks: 'extract.yml'
