---
# yamllint disable rule:line-length
###############################################################################
# Unpack Github Archive
###############################################################################
# Migrate files and handle case of brand new installation. Ignore non-existing
# source files, preserving ownership and file permissions.
#
# Directories are recursively migrated using cp instead of ansible.builtin.copy
# as the task does not scale to hundreds+ files.
#
# Args:
#   item: str - remote file path to migrate
#   _github_dir: str - local versioned extract location

- name: 'Extract | migrate | check {{ item }}'
  ansible.builtin.stat:
    path: '{{ github_extract_symlink_target }}/{{ item }}'
  register: _github_migrate_file

- name: 'Extract | migrate | migrate {{ item }}'  # noqa risky-file-permissions keep original
  when: >
    _github_migrate_file.stat.exists and
    not _github_migrate_file.stat.isdir
  ansible.builtin.copy:
    remote_src: true
    src: '{{ github_extract_symlink_target }}/{{ item }}'
    dest: '{{ _github_dir }}/{{ item }}'
    force: true

- name: 'Extract | migrate | directory'
  when: >
    _github_migrate_file.stat.exists and
    _github_migrate_file.stat.isdir
  ansible.builtin.command: 'cp -an "{{ github_extract_symlink_target }}/{{ item }}" {{ _github_dir }}/{{ item }}'
  changed_when: false
