---
# yamllint disable rule:line-length
- name: 'Extract delete | prepare'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Extract delete | prepare | install packages for verify'
      ansible.builtin.apt:
        name:
          - 'rsync'  # ansible.posix.synchronize
        update_cache: true
        state: 'present'
