---
- name: 'Extract delete migration | verify | extraction successful'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Extract delete migration | verify | query repo v1.0.0'
      ansible.builtin.stat:
        path: '/opt/test_repo_gz/test_repo-v1.0.0'
      register: _test_github_delete_repo_100

    - name: 'Extract delete migration | verify | query repo v1.0.1'
      ansible.builtin.stat:
        path: '/opt/test_repo_gz/test_repo-v1.0.1'
      register: _test_github_delete_repo_101

    - name: 'Extract delete migration | verify | query kept directory'
      ansible.builtin.stat:
        path: '/opt/test_repo_gz/this_dir_should_not_be_removed'
      register: _test_github_delete_dir

    - name: 'Extract delete migration | verify | query kept file'
      ansible.builtin.stat:
        path: '/opt/test_repo_gz/this_file_should_not_be_removed'
      register: _test_github_delete_file

    - name: 'Extract delete migration | verify | assert v1.0.0 deleted'
      ansible.builtin.assert:
        that: not _test_github_delete_repo_100.stat.exists
        success_msg: 'v1.0.0 removed correctly.'
        fail_msg: 'v1.0.0 exists. It should have been deleted.'

    - name: 'Extract delete migration | verify | assert v1.0.1 exists'
      ansible.builtin.assert:
        that: _test_github_delete_repo_101.stat.exists
        success_msg: 'v1.0.1 exists.'
        fail_msg: 'v1.0.1 removed. It should exist.'

    - name: 'Extract delete migration | verify | assert non-repo dir exists'
      ansible.builtin.assert:
        that: _test_github_delete_dir.stat.exists
        success_msg: 'non-repo directory still exists.'
        fail_msg: 'non-repo directory removed. It should exist.'

    - name: 'Extract delete migration | verify | assert non-repo file exists'
      ansible.builtin.assert:
        that: _test_github_delete_file.stat.exists
        success_msg: 'non-repo file still exists.'
        fail_msg: 'non-repo file removed. It should exist.'

- name: 'Extract delete migration | verify | migrate data'
  hosts: 'github-debian-12-extract_delete_migration'
  gather_facts: false
  tasks:
    - name: 'Extract delete migration migration | verify | query migrated file'
      ansible.builtin.slurp:
        path: '/opt/test_repo_gz/test_repo/config/db/db_skeleton_file.db'
      register: _test_github_migration

    - name: 'Extract delete migration | verify | assert migrated file version'
      ansible.builtin.assert:
        that: _test_github_migration.content | b64decode == '1.0.0'
        success_msg: 'db_skeleton_file.db version 1.0.0 migrated successfully.'
        fail_msg: 'db_skeleton_file.db version 1.0.0 migration FAILED.'

- name: 'Extract delete migration | verify | no migration'
  hosts: 'github-debian-12-extract_delete_migration-no-keep'
  gather_facts: false
  tasks:
    - name: 'Extract delete migration migration | verify | query migrated file'
      ansible.builtin.slurp:
        path: '/opt/test_repo_gz/test_repo/config/db/db_skeleton_file.db'
      register: _test_github_migration

    - name: 'Extract delete migration | verify | assert migrated file version'
      ansible.builtin.assert:
        that: _test_github_migration.content | b64decode == '1.0.1'
        success_msg: 'db_skeleton_file.db version 1.0.1 correct.'
        fail_msg: 'db_skeleton_file.db should be version 1.0.1.'
