---
###############################################################################
# Github REST API
###############################################################################
# TODO(sync): Keep features in sync with ansible_codeberg.
#
# Reference:
# * https://docs.github.com/en/rest?api
# * https://docs.github.com/en/rest/about-the-rest-api/api-versions

# Last time github options were validated against a default configuration.
github_role_validate_date: '2024-06-22'
github_role_validate_release: 'bookworm'

# Role checked against this version of the API.
github_role_api_version: '2022-11-28'

# Github API base URL.
github_role_release_url_base: 'https://api.github.com/repos'

###############################################################################
# APT Packages
###############################################################################

github_role_packages:
  - 'ca-certificates'  # SSL support for ansible.builtin.get_url.
  - 'unzip'  # zip archives.
  - 'xz-utils'  # xz archives.

github_role_testing_packages:
  - 'rsync'  # ansible.posix.synchronize (testing local archive copy).
