---
# yamllint disable rule:line-length
# Role variable returned variables are scoped to the current play only (e.g.
# converge.yml) and must be tested between each application of the role. Test
# these values while converging versus verify.yml (where scoping will prevent)
# testing these values.
#
# Reference:
# * https://github.com/ansible/molecule/issues/816

- name: 'Default | converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Default | converge | apply r_pufky.srv.github (tar.gz)'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.github'
      vars:
        github_testing_archive: '{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/molecule/files/test_archive_v1.0.0.tar.gz'
        github_repo_archive_type: 'tar.gz'
        github_repo_owner: 'leetreleaser'
        github_repo_repo: 'test_repo'
        github_repo_release: 'latest'
        github_file_owner: 'root'
        github_file_group: 'root'
        github_extract_dest: '/opt/test_repo_gz'
        github_extract_extra_opts: '--strip-components=1'
        github_extract_mode: 'a-st,o-rwx'
        github_extract_remove_files:
          - 'README.md'
          - '.hidden_file'

    - name: 'Default | converge | assert correct tar.gz returned variables'
      ansible.builtin.assert:
        that:
          - _github_target == 'v1.0.0'
          - _github_target_url == 'http://example.com/tar'
          - _github_archive == '/tmp/test_repo-v1.0.0.tar.gz'
          - _github_dir == '/opt/test_repo_gz/test_repo-v1.0.0'
          - _github_remote_metadata is mapping

    - name: 'Default | converge | apply r_pufky.srv.github (tar.xz)'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.github'
      vars:
        github_testing_archive: '{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/molecule/files/test_archive_v1.0.0.tar.xz'
        github_repo_archive_type: 'tar.xz'
        github_repo_owner: 'leetreleaser'
        github_repo_repo: 'test_repo'
        github_repo_release: 'latest'
        github_file_owner: 'root'
        github_file_group: 'root'
        github_extract_dest: '/opt/test_repo_xz'
        github_extract_extra_opts: '--strip-components=1'
        github_extract_mode: 'a-st,o-rwx'
        github_extract_remove_files:
          - 'README.md'
          - '.hidden_file'

    - name: 'Default | converge | assert correct tar.xz returned variables'
      ansible.builtin.assert:
        that:
          - _github_target == 'v1.0.0'
          - _github_target_url == 'http://example.com/tar'
          - _github_archive == '/tmp/test_repo-v1.0.0.tar.xz'
          - _github_dir == '/opt/test_repo_xz/test_repo-v1.0.0'
          - _github_remote_metadata is mapping

    - name: 'Default | converge | apply r_pufky.srv.github (zip)'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.github'
      vars:
        github_testing_archive: '{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/molecule/files/test_archive_v1.0.0.zip'
        github_staging_clean: false
        github_repo_archive_type: 'zip'
        github_repo_owner: 'leetreleaser'
        github_repo_repo: 'test_repo'
        github_repo_release: 'latest'
        github_file_owner: 'root'
        github_file_group: 'root'
        github_extract_dest: '/opt/test_repo_zip'
        github_extract_symlink_target: '/opt/test_repo_zip/test_repo'  # should not affect test
        github_extract_extra_opts: ''
        github_extract_mode: 'a-st,o-rwx'
        github_extract_remove_files:
          - 'README.md'
          - '.hidden_file'

    - name: 'Default | converge | assert correct zip returned variables'
      ansible.builtin.assert:
        that:
          - _github_target == 'v1.0.0'
          - _github_target_url == 'http://example.com/zip'
          - _github_archive == '/tmp/test_repo-v1.0.0.zip'
          - _github_dir == '/opt/test_repo_zip/test_repo-v1.0.0'
          - _github_remote_metadata is mapping
