---
- name: 'Default | prepare'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Default | prepare | base packages for bare-metal equivalency'
      ansible.builtin.apt:
        name:
          - 'rsync'  # ansible.posix.synchronize
        update_cache: true
        state: 'present'
